###
Get http://localhost:5050/pages/Views/Index

###
Get http://localhost:5050/api/Sql/List

###
Get http://localhost:5050/api/Sql/GetParamNames?id=7

###
Post http://localhost:5050/api/Sql/Query
Content-Type: application/application/x-www-form-urlencoded

id=7&values=1&values=2

###
Post http://localhost:5050/api/Sql/ListApi


###

POST http://localhost:58573/api/My/Sum
Content-Type: application/application/x-www-form-urlencoded

x=1&y=2&z=10

###

POST  http://localhost:58573/api/My/Echo
Content-Type: application/application/x-www-form-urlencoded

x=abc

###

http://localhost:58573/glimpse.axd